site_name: My Technical Writing Workspace
site_description: An introduction with a resume and writing samples.
site_author: Joe Wojak

theme:
  name: material
  features:
    - search.highlight

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Joe Wojak

nav:
  - Welcome: index.md
  - Work Experience: resume/resume.md
  - Writing Samples:
      - Introduction: samples/samples-intro.md
      - Budgets, Spending, and Pacing Delays:
          - Introduction: samples/budget-spend-intro.md
          - Understanding Budget Distribution and Update Cycles: samples/update-cycle.md
          - Budget Distribution Among and Within Data Centers: samples/budget-data-center.md
          - Budget Updates Can Delay Tactic Delivery: samples/budget-update.md
          - Force a Budget Update: samples/force-budget.md
      - Data Engineering Tutorial:
          - Introduction and Welcome: tutorial/welcome.md
          - Understanding Data Endpoints and Workflows: tutorial/endpoints.md
          - Configuring Your Development Environment:
              - Introduction: samples/setup-intro.md
              - Installing Scala: samples/setup-scala.md
              - Installing Java: samples/setup-java.md
              - Installing SBT: samples/setup-sbt.md
          - Create a Data Workflow Component: tutorial/create-workflow.md
          - Annotating Data: tutorial/annotate.md
          - Summary: tutorial/summary.md
      - Device Graph Overview:
          - Device Graph Basics: samples/graph-basics.md
          - Household Scores: samples/household-scores.md
          - Individual Scores: samples/individual-scores.md  
