site_name: My Test Docs

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
  - Home: index.md
  - Test: test.md
  - Subfolder:
      - Subdoc: subfolder/subdoc1.md
